Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

#Layout/SpaceAfterColon:
 # Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys: 
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/MixinUsage:
    Enabled: false
Metrics/BlockLength:
  Max: 100
Bundler/OrderedGems:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false